/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class UltraContextCore {
  constructor(path: string, options?: UltraContextCoreOptions | undefined | null)
  dispatchJson(operation: string, input: string): string
}

export interface UltraContextCoreOptions {
  contentDir?: string
  inlineLimit?: number
}
